services:
  app:
    build: .
    container_name: myapp
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8000:80
      # portmapping the port 80 of the container to the port 8000 of the host
    volumes:
      - .:/app
      # it mens tghat we are mounting the current directory to the /app directory in the container