services:
  app:
    build: .
    container_name: shopping-api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
      # portmapping the port 80 of the container to the port 8000 of the host
    volumes:
      - .:/app
      # it means that we are mounting the current directory to the /app directory in the container
    depends_on:
      - db
  db:
    db:
  image: postgres:latest
  env_file:
    - db.env
  ports:
    - 5432:5432
# run commands 
# docker-compose up --build